### ISSUE TITLE
About word-level tokenizer

### ISSUE THREAD

**Issue by DIO157128** [awsm-research/VulRepair#1]
Hi!
I read your paper and I was interested in your RQ3. How did you get the word-level tokenizer for CodeT5 and CodeBERT? As far as I know, these two models utilize BBPE tokenizer.
Best Regards

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,
We trained a word-level tokenizer using the "tokenizers" library provided by huggingface.
https://github.com/huggingface/tokenizers

**Comment by DIO157128** [comment]
> Hi @DIO157128, We trained a word-level tokenizer using the "tokenizers" library provided by huggingface. https://github.com/huggingface/tokenizers

Do you have relevant code? Viewing from your code, M7 and M9 use different tokenizers. I am not sure how you trained your tokenizers

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,

```
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.pre_tokenizers import Whitespace
from tokenizers.trainers import WordLevelTrainer

# init tokenizer
tokenizer = Tokenizer(WordLevel(unk_token="[UNK]"))
tokenizer.pre_tokenizer = Whitespace()
# specify "vocab_size", "special_tokens", and "min_frequency" to define word-level tokenizer
trainer = WordLevelTrainer(vocab_size=vocab_size,
                           special_tokens=special_tokens,
                           min_frequency=min_frequency)
# specify path to your tokenizer training data
tokenizer.train(files=["tokenizer_training_data.txt"], trainer=trainer)
# save tokenizer to a json file
tokenizer.save("./wordlevel_tokenizer.json")
print("Done tokenizer training")
# validate the tokenizer
tokenizer = Tokenizer.from_file("./wordlevel_tokenizer.json")
encoded = tokenizer.encode("example sentence!")
# encoded ids
print(encoded.ids)
```

Above is a quick start code snippet to train a word-level tokenizer using huggingface's library, hope this helps!

**Comment by DIO157128** [comment]
Hi, @MichaelFu1998-create 
Thank you for showing an example script. It is very helpful. :)
After reading the code above and the tokenizer you provided, two questions came into my mind:
1. What dataset is your word-level tokenizer trained on? Is it the same as the BPE tokenizer was trained on, which is CodeSearchNet?
2. I also notice that the word-level tokenizers of CodeBERT and CodeT5 you provided are different. The former one is about 20k words longer than the latter one. If they are trained on the same dataset then how come this happen? Does it mean that there's a relevance between tokenizers and models when talking about word-level tokenizers? For example, when training the word-level tokenizer of a specific model, should I load some configs of that model first?
I just started doing research in this field so I cannot understand tokenizers well. If you can answer my question then it should be of great help to me. 
BR

**Comment by MichaelFu1998-create** [comment]
Hello @DIO157128 ,
1. We trained the tokenizers on fine-tuning data, however, training on CodeSearchNet (pre-training data) should also be a reasonable approach depending on your need.
2. For CodeBERT, the original BPE tokenizer has a vocabulary of around 52k words, therefore, we created a word-level tokenizer for CodeBERT with a vocab size of 52k. For CodeT5, the original BPE tokenizer has a vocabulary of around 32k words, so we created a word-level tokenizer for CodeT5 with a vocab size of 32k.

If you are using the Huggingface Transformers library, here is some info about the CodeBERT and CodeT5
https://huggingface.co/microsoft/codebert-base/blob/main/config.json (CodeBERT)
https://huggingface.co/Salesforce/codet5-base/blob/main/config.json (CodeT5)
They are model config files where you can obtain info about the model architecture, vocab size etc.

**Comment by DIO157128** [comment]
Thank you for answering my questions. Now I have a better understanding of tokenizers and your research.

**Comment by GuodongFan** [comment]
I have a similar question.  In my mind, the T5code model is pre-trained with a BPE tokenizer but fine-tuned with word level or BPE. Is there a GAP between the pre-trained BPE and word-level tokenizer? Will pre-trained models be ineffective when fine-tuning with word-level tokenizers?

**Comment by GuodongFan** [comment]
@MichaelFu1998-create

**Comment by MichaelFu1998-create** [comment]
Hi @GuodongFan,
pls kindly refer to https://github.com/awsm-research/VulRepair/issues/2
