### ISSUE TITLE
Differences in M1 and M5

### ISSUE THREAD

**Issue by DIO157128** [awsm-research/VulRepair#4]
Hi!
I was trying to reproduce the M1 and M5 models using the same hyperparameters as yours. The result is quite different from yours.
For M1, I tried to retrain the M1 model from scratch and load it to infer. The result I got was 29.480%, quite different from that of you.
For M5, my result was 12.37%. 
The rest of the models' performances match your result. However, these 2 models were pretty abnormal.
Also, I compared my training logs with yours. I found a lot of training parameters that were not included in your code and readme. I was wondering if you have shared a repository that was out-of-date.
Hope you can help me with it. :)

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128
I'm not sure the main reason that you couldn't reproduce M1/5.
You may try re-splitting the data to see if you can obtain comparable results as we reported.

**Comment by DIO157128** [comment]
I see.
But I am still wondering about your dataset. In your paper, your dataset named CVEFixes contains 8482 vulnerability fixes. I looked it up in the original VRepair and CVEFixes paper. Both of them said their dataset contains 5365 vulnerabilities. This is a little confusing to me.  Did you use the data-mining tool provided by CVEFixes to extract data and split it the same way as that in VRepair?

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,
Thank you for pointing out this confusing information.
We also extracted data from the [big-vul dataset](https://github.com/ZeoVan/MSR_20_Code_vulnerability_CSV_Dataset), however, we forgot to modify the content in the paper. We will change the README.md file to clarify this.

**Comment by DIO157128** [comment]
Well, That's not a big deal. Don't mention it. :)
Since your dataset is a mixture of cvefixes and bigvul, did you filter your dataset because it length is not equal to the sum of theirs(3754+5365!=8482)?
I also wonder if the three splits of the dataset provided in your repository are the ones that you used to produce the result shown in the paper because the result that I reproduced is very different from that in your paper. I read the code of M1 and found that the splits were created randomly, so I replaced the datasets with those in your repository and got a different result from yours.

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,
We did not filter the data. The data splits provided should be the ones used by us. If you need to retrain the model from scratch and encounter a problem reproducing the same results, you may try to combine and re-split the dataset to 70(train)/10(val)/20 (test) and see if you can obtain comparable results. Thank you :)

**Comment by DIO157128** [comment]
Hi @MichaelFu1998-create,
I compared the [test data](https://github.com/awsm-research/VulRepair/blob/main/data/fine_tune_data/test.csv) you provided with that in the [raw prediction of Vulrepai](https://github.com/awsm-research/VulRepair/blob/main/data/VulRepair_raw_predictions/vulrepair_raw_preds_for_cve_fixes_test.csv)r and found they are totally different. Also, I noticed that you have updated your repository and hugging face. I downloaded the latest data and tried to split the data as you did in the code of M1. But the result was still bad: 35.05% 
I also tried re-combining and re-split the old dataset and the result was 37.1%. Both of the results were not comparable with yours.
I wonder if you can provide all the splits of the dataset (train, valid, test) that were used to produce the result in your paper(43.75%).

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,
I was able to obtain reported results using the updated code.
Let me double-check it and get back to you later tomorrow.

**Comment by MichaelFu1998-create** [comment]
Hi @DIO157128,
I just updated the M1 folder.
If you could pull the repo and try re-train the M1 using the following commands:

```
# training
cd M1_VulRepair_PL-NL
python vulrepair_main.py \
    --model_name=model.bin \
    --output_dir=./saved_models \
    --tokenizer_name=Salesforce/codet5-base \
    --model_name_or_path=Salesforce/codet5-base \
    --do_train \
    --epochs 75 \
    --encoder_block_size 512 \
    --decoder_block_size 256 \
    --train_batch_size 4 \
    --eval_batch_size 4 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --evaluate_during_training \
    --seed 123456  2>&1 | tee train.log
```

```
# Inference
python vulrepair_main.py \
    --output_dir=./saved_models \
    --model_name=model.bin \
    --tokenizer_name=Salesforce/codet5-base \
    --model_name_or_path=Salesforce/codet5-base \
    --do_test \
    --encoder_block_size 512 \
    --decoder_block_size 256 \
    --num_beams=50 \
    --eval_batch_size 1
```

Thank you!
